homework_07/coverage_app/app/urls.py
from django.urls import path
from . import views

app_name = 'app'


urlpatterns = [
    path('', views.ProjectListView.as_view(), name='project_list'),
    path('project/<int:pk>/', views.ProjectDetailView.as_view(),
         name='project_detail'),
    path('e2e', views.e2e),
    path('api', views.api),
    path('unit', views.unit),
    path('e2e/list', views.E2EListView.as_view(),
         name='e2e_list'),
    path('e2e/<int:pk>/', views.E2EDetailView.as_view(),
         name='e2e_detail'),
    path('api/list', views.APIListView.as_view(),
         name='api_list'),
    path('unit/list', views.UNITListView.as_view(),
         name='unit_list'),
]

homework_07/coverage_app/coverage_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app'))
]

homework_07/coverage_app/app/models.py
from django.db import models
from django.utils.timezone import now


class Base(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        abstract = True


class Project(Base):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(null=True)

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'
        ordering = ['name']


class E2ECoverage(Base):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=False)
    manual = models.PositiveIntegerField(default=0)
    automated = models.PositiveIntegerField(default=0)
    coverage = models.FloatField(default=0)

    def __str__(self):
        return f'"{self.project.name}" project has e2e manual tests = {self.manual} and e2e automated tests = {self.automated}'

    class Meta:
        verbose_name = 'E2E coverage'
        verbose_name_plural = 'E2E coverage'
        ordering = ['project']

    def get_coverage_count(self) -> float:
        try:
            coverage_count = self.automated / (self.manual + self.automated) * 100
        except ZeroDivisionError:
            coverage_count = 0
        return round(coverage_count, 2)


class APICoverage(Base):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=False)
    full_coverage = models.FloatField(default=0)
    partial_coverage = models.FloatField(default=0)
    empty_coverage = models.FloatField(default=100)
    actual_cnt = models.PositiveIntegerField(default=0)
    full_cnt = models.PositiveIntegerField(default=0)
    partial_cnt = models.PositiveIntegerField(default=0)
    empty_cnt = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'"{self.project.name}" project has full api coverage {self.full_coverage} {self.full_cnt}/{self.actual_cnt})%'

    class Meta:
        verbose_name = 'API coverage'
        verbose_name_plural = 'API coverage'
        ordering = ['project']


class UnitCoverage(Base):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=False)
    code_coverage = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'"{self.project.name}" project has unit tests code coverage = {self.code_coverage}'

    class Meta:
        verbose_name = 'UNIT coverage'
        verbose_name_plural = 'UNIT coverage'
        ordering = ['project']

homework_07/coverage_app/app/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Project, APICoverage, E2ECoverage, UnitCoverage


def index(request):
    return render(request, 'e2e.html')


class E2EListView(ListView):
    model = E2ECoverage
    p_title = 'E2E coverage'


class E2EDetailView(DetailView):
    model = E2ECoverage
    p_title = 'E2E detail coverage'


class APIListView(ListView):
    model = APICoverage
    p_title = 'API coverage'


class UNITListView(ListView):
    model = UnitCoverage
    p_title = 'UNIT coverage'


class ProjectListView(ListView):
    model = Project
    p_title = 'Projects'


class ProjectDetailView(DetailView):
    model = Project
    p_title = 'Project detail'


def e2e(request, slug=''):
    projects = Project.objects.order_by('-name')

    data = {}
    for project in projects:
        e2e_tests = E2ECoverage.objects.filter(project=project.id).order_by('-created_at')
        automated_test_count = e2e_tests[0].automated if len(e2e_tests) else 0
        manual_test_count = e2e_tests[0].manual if len(e2e_tests) else 0
        coverage_count = e2e_tests[0].get_coverage_count() if len(e2e_tests) else 0
        data[f'{project.name}'] = [automated_test_count, manual_test_count, coverage_count]

    context = {"data": data, }

    return render(request, 'e2e.html', context=context)


def api(request, slug=''):
    projects = Project.objects.order_by('-name')

    data = {}
    for project in projects:
        api_coverage_project = APICoverage.objects.filter(project=project.id).order_by('-created_at')
        exist_coverage_in_db = bool(len(api_coverage_project))

        full_api_coverage = api_coverage_project[0].full_coverage if exist_coverage_in_db else 0
        full_cnt = api_coverage_project[0].full_cnt if exist_coverage_in_db else 0
        actual_cnt = api_coverage_project[0].actual_cnt if exist_coverage_in_db else 0

        partial_api_coverage_count = api_coverage_project[0].partial_coverage if exist_coverage_in_db else 0
        partial_cnt = api_coverage_project[0].partial_cnt if exist_coverage_in_db else 0

        empty_api_coverage = api_coverage_project[0].empty_coverage if exist_coverage_in_db else 0
        empty_cnt = api_coverage_project[0].empty_cnt if exist_coverage_in_db else 0

        data[f'{project.name}'] = [full_api_coverage, full_cnt, actual_cnt,
                                   partial_api_coverage_count, partial_cnt,
                                   empty_api_coverage, empty_cnt]

    context = {"data": data, }

    return render(request, 'api.html', context=context)


def unit(request, slug=''):
    projects = Project.objects.order_by('-name')

    data = {}
    for project in projects:
        unit_coverage_project = UnitCoverage.objects.filter(project=project.id).order_by('-created_at')
        exist_coverage_in_db = bool(len(unit_coverage_project))
        code_coverage = unit_coverage_project[0].code_coverage if exist_coverage_in_db else 0
        data[f'{project.name}'] = [code_coverage, 100-code_coverage]
    context = {"data": data, }

    return render(request, 'unit.html', context=context)

homework_07/coverage_app/app/templates/api.html
{% extends 'base.html' %}
{% block section %}
    <h2>API</h2>
{% endblock %}
{% block coverage %}
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th scope="col">Название продукта</th>
                <th scope="col">Полностью покрытые API</th>
                <th scope="col">Частично покрытые API</th>
                <th scope="col">Непокрытые API</th>
            </tr>
            </thead>
            <tbody>
            {% for key, value in data.items %}
                <tr>
                    <td>{{ key }}</td>
                    <td>{{ value.0 }} % ({{ value.1 }}/{{ value.2 }})</td>
                    <td>{{ value.3 }} % ({{ value.4 }}/{{ value.2 }})</td>
                    <td>{{ value.5 }} % ({{ value.6 }}/{{ value.2 }})</td>
                </tr>
            {% endfor %}

            </tbody>
        </table>

    </div>
<a href="{% url 'app:api_list' %}">API coverage list</a>
{% endblock %}

homework_07/coverage_app/app/templates/app/apicoverage_list.html
{% extends 'base.html' %}
{% block section %}
<body>
<h3>API coverage history</h3>
<div class="api-list">
    <ul>
        {% for item in apicoverage_list %}
            <li>
                {{ item }}
            </li>
        {% endfor %}
    </ul>
</div>
<a href="/">Main</a><br>
</body>
{% endblock %}

homework_07/coverage_app/app/templates/app/e2ecoverage_detail.html
{% extends 'base.html' %}
{% block section %}
<body>
<h3>E2E with id = {{ object.id }} </h3>
<div class="e2e-details">
    <ul>
        <li> id = {{ object.id }} </li>
        <li> name = {{ object.project.name }} </li>
        <li> manual = {{ object.manual }} </li>
        <li> automated = {{ object.automated }} </li>
        <li> created_at = {{ object.created_at }} </li>
        <li> updated_at = {{ object.updated_at }} </li>
    </ul>
    <a href="{% url 'app:e2e_list' %}">Back to list</a>
</div>
</body>
{% endblock %}

homework_07/coverage_app/app/templates/app/e2ecoverage_list.html
{% extends 'base.html' %}
{% block section %}
<body>
<h3>E2E coverage history</h3>
<div class="e2e-list">
    <ul>
        {% for item in e2ecoverage_list %}
            <li>
                id = <a href="{% url 'app:e2e_detail' item.id%}"> {{ item.id }}</a> created_at = {{ item.created_at }}
            </li>
        {% endfor %}
    </ul>
</div>
<a href="/">Main</a><br>
</body>

{% endblock %}

homework_07/coverage_app/app/templates/app/project_detail.html
{% extends 'base.html' %}
{% block sidebar %}
{% endblock %}
{% block section %}
<body>
<h3>Проект {{ object.name }}</h3>
<div class="project-list">
    <ul>
        <li> id = {{ object.id }} </li>
        <li> name = {{ object.name }} </li>
        <li> description = {{ object.description }} </li>
        <li> created_at = {{ object.created_at }} </li>
        <li> updated_at = {{ object.updated_at }} </li>
    </ul>
</div>
<a href="{% url 'app:project_list' %}">Back to list</a>
</body>
{% endblock %}

homework_07/coverage_app/app/templates/app/project_list.html
{% extends 'base.html' %}

{% block sidebar %}
{% endblock %}
{% block section %}
<body>
<h3>Список проектов</h3>
<div class="project-list">
    <ul>
        {% for item in project_list %}
            <li>
                <a href="{% url 'app:project_detail' item.id%}">{{ item.name }}</a>
            </li>
        {% endfor %}
    </ul>
</div>
</body>
{% endblock %}

homework_07/coverage_app/app/templates/app/unitcoverage_list.html
{% extends 'base.html' %}
{% block section %}
<body>
<h3>UNIT coverage history</h3>
<div class="unit-list">
    <ul>
        {% for item in unitcoverage_list %}
            <li>
                {{ item }}
            </li>
        {% endfor %}
    </ul>
</div>
<a href="/">Main</a><br>
</body>
{% endblock %}

homework_07/coverage_app/app/templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>Code Coverage Dashboard · My Company</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">


    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Favicons -->
    <meta name="theme-color" content="#7952b3">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .btn-bd-primary {
            font-weight: 600;
            color: #fff;
            background-color: #6c757d;
            border-color: #6c757d;
        }
    </style>


    <!-- Custom styles for this template -->
</head>
<body>

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="/">My Company</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
</header>
{% block sidebar %}
<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Виды тестов</span>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="/e2e">
                            <span data-feather="file-text">E2E</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/api">
                            <span data-feather="file-text">API</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/unit">
                            <span data-feather="file-text">UNIT</span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Code Coverage Dashboard</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group me-2">

                    </div>

                </div>
            </div>
{% endblock %}
            {% block section %}
            {% endblock %}
            {% block coverage %}
                <div class="d-flex flex-column flex-sm-row">
                    <a href="/e2e"
                       class="btn btn-lg btn-bd-primary">E2E тесты</a>
                    <a href="/api"
                       class="btn btn-lg btn-outline-secondary mt-3 mt-sm-0 ms-sm-3">API тесты</a>
                    <a href="/unit"
                       class="btn btn-lg btn-outline-secondary mt-3 mt-sm-0 ms-sm-3">UNIT тесты</a>
                </div>
            {% endblock %}
        </main>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
        integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
        integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
</body>
</html>

homework_07/coverage_app/app/templates/e2e.html
{% extends 'base.html' %}
{% block section %}
    <h2>E2E</h2>
{% endblock %}
{% block coverage %}
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th scope="col">Название продукта</th>
                <th scope="col">Автотесты</th>
                <th scope="col">Ручные тесты</th>
                <th scope="col">Покрытие требований (e2e)</th>
            </tr>
            </thead>
            <tbody>
            {% for key, value in data.items %}
                <tr>
                    <td>{{ key }}</td>
                    <td>{{ value.0 }}</td>
                    <td>{{ value.1 }}</td>
                    <td>{{ value.2 }} %</td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
<a href="{% url 'app:e2e_list' %}">E2E coverage list</a>
{% endblock %}

homework_07/coverage_app/app/templates/unit.html
{% extends 'base.html' %}
{% block section %}
    <h2>UNIT</h2>
{% endblock %}
{% block coverage %}
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th scope="col">Название продукта</th>
                <th scope="col">Покрытие кода</th>
                <th scope="col">Непокрытый код</th>
            </tr>
            </thead>
            <tbody>
            {% for key, value in data.items %}
                <tr>
                    <td>{{ key }}</td>
                    <td>{{ value.0 }} % </td>
                    <td>{{ value.1 }} % </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>

    </div>
<a href="{% url 'app:unit_list' %}">UNIT coverage list</a>
{% endblock %}